### ISSUE TITLE
media-server crashes when i call IncomingStream.Stop() or  Transport.Stop() 

### ISSUE THREAD

**Issue by liwf616** [notedit/media-server-go#38]
Hi，

when i call IncomingStream.Stop(),  I got the following crash log(mac):

1555322258.905][LOG]<DTLSConnection::GenerateCertificate()
[0x47da5c0][1555322258.905][LOG]<DTLSConnection::Initialize(5)
=== RUN   Test_SFUStop
[0x47da5c0][1555322258.905][LOG]-EnableLog [1]
[0x47da5c0][1555322258.905][LOG]>RTPBundleTransport::Init()
[0x47da5c0][1555322258.906][LOG]-RTPBundleTransport::Init() | Got port [57774]
[0x47da5c0][1555322258.906][LOG]<RTPBundleTransport::Init()
[0x700008394000][1555322258.906][LOG]>EventLoop::Run() | [0x6800018]
[0x47da5c0][1555322258.908][LOG]-RTPBundleTransport::AddICETransport [52fdfc072182654f:ez5G]
[0x47da5c0][1555322258.908][LOG]-RemoteRateEstimator adding stream [ssrc:0]
[0x47da5c0][1555322258.908][LOG]-DTLSConnection::SetSRTPProtectionProfiles() [profiles:'']
[0x47da5c0][1555322258.908][LOG]-DTLSICETransport::SetLocalSTUNCredentials() | [frag:52fdfc072182654f,pwd:163f5f0f9a621d729566c74d10037c4d7bbb0407d1e2c649]
[0x47da5c0][1555322258.908][LOG]-DTLSICETransport::SetRemoteSTUNCredentials() |  [frag:ez5G,pwd:1F1qS++jzWLSQi0qQDZkX/QV]
[0x47da5c0][1555322258.908][LOG]-DTLSICETransport::SetRemoteCryptoDTLS | [setup:actpass,hash:sha-256,fingerprint:D2:FA:0E:C3:22:59:5E:14:95:69:92:3D:13:B4:84:24:2C:C2:A2:C0:3E:FD:34:8E:5E:EA:6F:AF:52:CE:E6:0F]
[0x47da5c0][1555322258.908][LOG]-DTLSConnection::SetRemoteSetup() | [remote:2]
[0x47da5c0][1555322258.908][LOG]>DTLSConnection::Init()
[0x47da5c0][1555322258.909][LOG]<DTLSConnection::Init()
[0x47da5c0][1555322258.909][LOG]-RTPBundleTransport::AddRemoteCandidate [username:52fdfc072182654f:ez5G,candidate:35.188.215.104:59110}
[0x47da5c0][1555322258.909][LOG]-RTPBundleTransport::AddRemoteCandidate [username:52fdfc072182654f:ez5G,candidate:35.188.215.104:59110}
[0x700008394000][1555322258.910][ERR]-RTPBundleTransport::AddRemoteCandidate already present [candidate:35.188.215.104:59110]
[0x47da5c0][1555322258.910][LOG]-DTLSICETransport::AddIncomingSourceGroup() [mid:'',rid:'',ssrc:3510681183,fec:0,rtx:0]
[0x47da5c0][1555322258.910][LOG]-RemoteRateEstimator adding stream [ssrc:3510681183]
[0xc4202fb410]
[0x47da5c0][1555322258.910][LOG]-DTLSICETransport::AddIncomingSourceGroup() [mid:'',rid:'',ssrc:3004364195,fec:1080772241,rtx:1126032854]
[0x47da5c0][1555322258.910][LOG]-RemoteRateEstimator adding stream [ssrc:3004364195]
[0xc4202fb470]
[0x47da5c0][1555322258.911][LOG]-DTLSICETransport::RemoveIncomingSourceGroup() [mid:'',rid:'',ssrc:3510681183,fec:0,rtx:0]
libc++abi.dylib: terminating with uncaught exception of type std::__1::bad_weak_ptr: bad_weak_ptr
SIGABRT: abort
PC=0x7fff7e255b86 m=0 sigcode=0
signal arrived during cgo execution

goroutine 6 [syscall, locked to thread]:
runtime.cgocall(0x418f090, 0xc4200b9ce8, 0xc4202fb3e0)
    /Users/wfli/ks/go/src/runtime/cgocall.go:132 +0xe4 fp=0xc4200b9ca0 sp=0xc4200b9c60 pc=0x40044a4
github.com/notedit/media-server-go/wrapper._Cfunc__wrap_DTLSICETransport_RemoveIncomingSourceGroup_native_a625d9984f014aad(0x6008000, 0x6805400, 0xc420001600)
    github.com/notedit/media-server-go/wrapper/_obj/_cgo_gotypes.go:931 +0x4a fp=0xc4200b9ce8 sp=0xc4200b9ca0 pc=0x4104aca
github.com/notedit/media-server-go/wrapper.SwigcptrDTLSICETransport.RemoveIncomingSourceGroup(0x6008000, 0x43a84a0, 0xc4202f1258, 0xc4200b9d88)
    /Users/wfli/ks/goworkspace/src/github.com/notedit/media-server-go/wrapper/native.go:3660 +0x42 fp=0xc4200b9d10 sp=0xc4200b9ce8 pc=0x41198f2
github.com/notedit/media-server-go/wrapper.(*SwigcptrDTLSICETransport).RemoveIncomingSourceGroup(0xc4202f0e88, 0x43a84a0, 0xc4202f1258, 0x24)
    <autogenerated>:1 +0x50 fp=0xc4200b9d40 sp=0xc4200b9d10 pc=0x411c0c0
github.com/notedit/media-server-go.(*IncomingStream).CreateTrack.func1()
    /Users/wfli/ks/goworkspace/src/github.com/notedit/media-server-go/incomingstream.go:282 +0x112 fp=0xc4200b9df0 sp=0xc4200b9d40 pc=0x418b942
github.com/notedit/media-server-go.(*IncomingStreamTrack).Stop(0xc420094840)
    /Users/wfli/ks/goworkspace/src/github.com/notedit/media-server-go/incomingstreamtrack.go:518 +0x12b fp=0xc4200b9e48 sp=0xc4200b9df0 pc=0x417f85b
github.com/notedit/media-server-go.(*IncomingStream).Stop(0xc4202d7800)
    /Users/wfli/ks/goworkspace/src/github.com/notedit/media-server-go/incomingstream.go:315 +0xaa fp=0xc4200b9f00 sp=0xc4200b9e48 pc=0x417ddaa
github.com/notedit/media-server-go.Test_SFUStop(0xc42010a0f0)

**Comment by notedit** [comment]
incoming.Stop()  crashes

**Comment by notedit** [comment]
fixed
